### ISSUE TITLE
Parse errors

### ISSUE THREAD

**Issue by testniger** [domainvalidity/php-domain-validator#5]
ParseError: syntax error, unexpected 'protected' (T_PROTECTED), expecting variable (T_VARIABLE) in /var/www/vendor/domainvalidity/php-domain-validator/src/Validator.php:13

**Comment by adrorocker** [comment]
@testniger sorry for the delay in my response for some reason I missed this issue. Could you provide instructions on how to reproduce this error?

**Comment by adrorocker** [comment]
@testniger Also just by the actual error message my guess would be that you are using a version of php that does not support [constructor property promotion](https://www.php.net/manual/en/language.oop5.decon.php#language.oop5.decon.constructor.promotion)

I'll close this issue. Feel free to reopen if this is actually an issue after testing with php >= 8.1
